#!/usr/bin/env node
/**
 * Library page — checks that "Oyster Overview.html" matches the catalog.
 * Read-only.
 *
 * Usage (terminal, from the "Oyster Website" folder):
 *   node tools/library-test.js        # exit 1 on failure
 *
 * Requirements: Node 18+. No npm install.
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { build, sizeBucket } = require('./build-library.js');

const ROOT = path.join(__dirname, '..');
let failed = 0, passed = 0;
function check(label, ok, detail) {
  if (ok) { passed++; console.log('PASS  ' + label); }
  else { failed++; console.log('FAIL  ' + label + (detail ? '\n      ' + detail : '')); }
}

const sandbox = {};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(ROOT, 'data', 'oysters.js'), 'utf8'), sandbox);
const catalogIds = sandbox.OYSTERS.map(o => o.id).sort();
const html = fs.readFileSync(path.join(ROOT, 'Oyster Overview.html'), 'utf8');

const articleIds = [...html.matchAll(/<article class="oyster" id="([^"]+)"/g)].map(m => m[1]).sort();
const linkIds = [...html.matchAll(/<li data-target="([^"]+)">/g)].map(m => m[1]).sort();
const tbody = (html.match(/<tbody>([\s\S]*?)<\/tbody>/) || [])[1] || '';
const rowIds = [...tbody.matchAll(/<tr><td><a href="#([^"]+)">/g)].map(m => m[1]).sort();
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);

check(catalogIds.length + ' articles, same ids as the catalog', same(articleIds, catalogIds),
  'articles ' + articleIds.length);
check(catalogIds.length + ' sidebar links, same ids as the catalog', same(linkIds, catalogIds),
  'links ' + linkIds.length);
check(catalogIds.length + ' Quick Reference rows, same ids as the catalog', same(rowIds, catalogIds),
  'rows ' + rowIds.length);
check('no NUL bytes', !html.includes('\0'));
check('generated-file notice at the top', /^<!DOCTYPE html>\n<!-- Generated by tools\/build-library\.js/.test(html));
check('no template markers left', !html.includes('@@'));
check('ends with </html>', html.trimEnd().endsWith('</html>'));
check('page is up to date with data/oysters.js (node tools/build-library.js)', build().html === html);
check('Currently Serving reads menu/serving as an object', html.includes("Object.keys(snapshot.val() || {})"));

const unknownSal = sandbox.OYSTERS.filter(o => !o.salinity).map(o => o.id);
const withSalAttr = [...html.matchAll(/<article class="oyster" id="([^"]+)"\n\s+data-salinity=/g)].map(m => m[1]);
check('oysters with unknown salinity get no salinity dots', unknownSal.every(id => !withSalAttr.includes(id)),
  unknownSal.join(', '));

// Size buckets
const cases = [
  ['Medium — 2.5–3"', 'medium'], ['Small — 2.5–3" (cocktail)', 'small'],
  ['Small to medium — 2.5–3"', 'small-medium'], ['Large — 3–4"', 'large'],
  ['Medium to large — 3–3.5"', 'large'], ['Undocumented', ''], [null, ''],
  ['Very small — rarely exceeds 2–3"; deep cup with large meat relative to shell', 'small']
];
const wrong = cases.filter(([s, b]) => sizeBucket(s) !== b);
check('size buckets', !wrong.length, wrong.map(([s, b]) => JSON.stringify(s) + ' -> ' + sizeBucket(s) + ', expected ' + b).join('; '));

// Curated Flights must read size the same way as the library filter.
const F = require(path.join(ROOT, 'data', 'flights.js'));
const RANK = { 'small': 1, 'small-medium': 2, 'medium': 2, 'large': 3 };
const disagree = sandbox.OYSTERS.filter(o => {
  const b = sizeBucket(o.size), r = F._internals.sizeRank(o);
  return b ? RANK[b] !== r : !isNaN(r);
}).map(o => o.id + ' (' + JSON.stringify(o.size) + ': library ' + (sizeBucket(o.size) || 'unknown') + ', flights ' + F._internals.sizeRank(o) + ')');
check('Curated Flights and the library read every size the same way', !disagree.length, disagree.join('; '));

console.log('\n' + (failed ? failed + ' of ' + (passed + failed) + ' checks failed.' : 'All ' + passed + ' checks passed.'));
process.exit(failed ? 1 : 0);
